Configurations:

- MQTT:
    broker: localhost
    port: 1883
    username: "kunal"
    password: "picocamera123"
    topic: "Sensor/Values"
    serial_port: "COM3"

- KAFKA:
    broker: 'localhost:29092'
    topic: "RealTime_Data"

- INFLUXDB:
    host: "http://localhost:8086"
    org: "PICOCAMERA"
    bucket: "Sensor_Data"

